### PR TITLE
Implementation of DRiLLS RL Algorithms' with Google dopamine [WIP]

### PR DESCRIPTION
**Pull request by born-2learn**
This Pull Request marks the starting of the Reinforcement Learning Algorithms' implementation with Google Dopamine in DRiLLS.

This new feature will make it easier to implement the model and session classes in DRiLLS, and hence enable faster prototyping.

## Timeline:  
| Est. Time to completion | Topic |
| ------------- | ------------- |
| 13th Jan- 20th Jan, 2020 | Familiarity with DRiLLS and RL Algorithms |
| 20th Jan- 30th Jan, 2020 | Familiarity with Google Dopamine  |
| 5th Feb- 12th Feb, 2020 | Stage I Implementation |
| 12th Feb- 18th Feb, 2020 | Stage II Implementation |
| 18th Feb- 21st Feb, 2020 | Project Completion |

### CODE REVIEW

**Comment by abdelrahmanhosny** [comment]
Thanks Syed for your interest in doing this. A new implementation with Dopamine certainly makes it better for the community to develop RL algorithms for logic synthesis.

I'm available to help.

**Comment by abdelrahmanhosny** [comment]
Hi @born-2learn 
I'm just checking in to see if there is any help I can provide for you to make this PR a success? :)

**Comment by born-2learn** [comment]
Hi @abdelrahmanhosny ! Thanks for your concern. I'm currently working on getting familiar with Google Dopamine. I'm running a bit behind the proposed timeline due to college.

I will get back to you with my doubts very soon.

**Comment by born-2learn** [comment]
For the **Model's Network Size**: why have you used **Actor**: _2 fully connected layers_, **20 hidden
units each.**   
**Critic**: _one hidden layer_ with **10 units**.

From the [Research Paper](https://arxiv.org/abs/1911.04021), I get that deeper neural networks exhibit a random behavior and do not train well in the DRiLLS framework; @abdelrahmanhosny may I know the reason for choosing 20 and 10 as the number of hidden units.


Also in line 83 of [drills.py](https://github.com/scale-lab/DRiLLS/blob/master/drills.py); Will iteratively running the Adam Optimizer, after loading the Model(model.ckpt) from file, achieve the required functionality?

**Comment by abdelrahmanhosny** [comment]
20 and 10 were chosen after we experimented with different values. 

Iteratively running the optimizer won't train a model for _design space exploration_. It will load an existing model and use it to explore the design space.

**Comment by born-2learn** [comment]
@abdelrahmanhosny I have made changes to the proposed timeline. There are a few delays due to my College exams and assignments.
Thank you.

**Comment by abdelrahmanhosny** [comment]
@born-2learn no problem. Good luck with the exams and assignments.

**Pull request closed without merging**
